insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Legend of Hell House, The', 338, 12, 10958, 'Profound', 'FANTASY', 197);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('True Love', 468, 22, 12921, 'national', 'THRILLER', 198);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Four Days of Naples, The (Le quattro giornate di Napoli)', 278, 100, 448, 'Synergized', 'FANTASY', 214);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Behind the Candelabra', 8, 40, 25136, 'throughput', 'WESTERN', 364);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Went to Coney Island on a Mission From God... Be Back by Five', 258, 58, 11549, 'Profit-focused', 'DRAMA', 88);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Mr. Moto''s Last Warning', 191, 28, 6190, 'next generation', 'THRILLER', 5);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Medicine for Melancholy', 424, 80, 8641, 'clear-thinking', 'WESTERN', 461);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('These Girls', 234, 7, 21112, 'attitude-oriented', 'THRILLER', 176);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Quarantine', 399, 82, 17509, 'adapter', 'THRILLER', 23);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Mikado, The', 318, 92, 11171, 'demand-driven', 'DRAMA', 191);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Hired Hand, The', 186, 66, 17775, 'info-mediaries', 'FANTASY', 128);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Good Woman, A', 124, 0, 27095, 'Persistent', 'DRAMA', 496);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Boys Life 3', 362, 93, 9560, 'middleware', 'TRAGEDY', 378);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('See the Sea', 262, 70, 4131, 'Optional', 'WESTERN', 73);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Once Were Warriors', 326, 19, 6689, 'open system', 'TRAGEDY', 373);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Painted Lady', 387, 56, 32053, 'help-desk', 'TRAGEDY', 236);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Fatty and Mabel Adrift', 225, 30, 20153, 'algorithm', 'DRAMA', 423);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Moscow Clad in Snow (Moscou sous la neige) ', 36, 70, 26956, 'executive', 'THRILLER', 72);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Kismet', 106, 93, 34604, 'upward-trending', 'THRILLER', 344);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Summer by the River, A (Kuningasjätkä)', 194, 40, 33564, 'Fully-configurable', 'WESTERN', 463);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Stargate: Continuum', 155, 62, 121, 'archive', 'FANTASY', 316);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Into the Night', 321, 52, 21565, 'data-warehouse', 'THRILLER', 382);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Boiling Point', 350, 79, 12741, 'groupware', 'TRAGEDY', 494);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Cyrus', 163, 23, 17354, 'Reduced', 'WESTERN', 218);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Jazz Singer, The', 167, 22, 16475, 'challenge', 'WESTERN', 83);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Sällskapsresan II - Snowroller', 466, 45, 2778, 'attitude', 'FANTASY', 1);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Mademoiselle Chambon', 204, 17, 24553, 'Exclusive', 'WESTERN', 306);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Beauty and the Beast (La belle et la bête)', 471, 33, 2223, 'attitude', 'DRAMA', 452);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Diebuster "Top wo Narae 2"', 297, 88, 19307, 'mobile', 'FANTASY', 206);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Storm in Summer, A', 145, 34, 15838, 'logistical', 'FANTASY', 175);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Maze, The', 365, 1, 13775, 'policy', 'WESTERN', 271);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Devil Hides in Doubt (Sollbruchstelle)', 497, 66, 31921, 'Persevering', 'DRAMA', 11);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Whip Hand, The', 294, 25, 15987, 'core', 'DRAMA', 456);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Blue Crush', 47, 23, 3458, 'Open-source', 'DRAMA', 386);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Tyler Perry''s Diary of a Mad Black Woman', 431, 89, 20076, 'asymmetric', 'FANTASY', 31);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Dawn Patrol, The (Flight Commander)', 277, 68, 4933, 'infrastructure', 'DRAMA', 459);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Bedlam', 422, 44, 7787, 'intermediate', 'WESTERN', 449);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Vääpeli Körmy ja marsalkan sauva', 157, 42, 1744, 'discrete', 'THRILLER', 59);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Monster, The', 140, 70, 17212, 'algorithm', 'TRAGEDY', 200);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Suture', 138, 42, 11650, 'software', 'WESTERN', 240);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Wildcats', 243, 71, 26595, 'adapter', 'WESTERN', 27);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('What! No Beer?', 264, 0, 14988, 'demand-driven', 'FANTASY', 361);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Knowing', 500, 16, 29318, 'migration', 'THRILLER', 153);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Head of State', 15, 59, 29309, 'frame', 'THRILLER', 336);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Santa''s Apprentice', 224, 53, 26611, 'stable', 'WESTERN', 454);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Johnny Mad Dog', 474, 85, 26598, 'heuristic', 'DRAMA', 58);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('The Harmony Game', 11, 37, 18182, 'product', 'DRAMA', 186);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Break-in', 170, 89, 12630, 'infrastructure', 'THRILLER', 465);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Paradise: Faith (Paradies: Glaube)', 51, 8, 22688, 'Proactive', 'TRAGEDY', 447);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Next of Kin', 301, 36, 13590, 'tangible', 'TRAGEDY', 67);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Around the World in 80 Days', 219, 74, 1616, 'utilisation', 'WESTERN', 143);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Whipped', 148, 71, 30842, 'Multi-lateral', 'TRAGEDY', 56);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Man with Two Brains, The', 301, 46, 11985, 'Proactive', 'DRAMA', 350);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Window, The', 273, 54, 23704, 'access', 'DRAMA', 60);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Born Romantic', 420, 59, 11596, 'Open-source', 'TRAGEDY', 408);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Graduate, The', 388, 45, 10923, 'Persistent', 'FANTASY', 496);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Temple Grandin', 82, 74, 25835, 'zero defect', 'DRAMA', 417);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Harry and Walter Go to New York', 218, 37, 15246, '24/7', 'TRAGEDY', 451);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Manhattan Project, The', 55, 39, 18510, 'Enhanced', 'THRILLER', 488);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Girl', 159, 60, 29441, 'Customer-focused', 'DRAMA', 462);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Typhoon (Tae-poong)', 4, 9, 11141, 'core', 'DRAMA', 456);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Astronaut''s Wife, The', 267, 12, 15213, 'composite', 'WESTERN', 453);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Pitfall (Otoshiana)', 397, 40, 22952, 'application', 'DRAMA', 74);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Rockin'' in the Rockies', 329, 56, 31320, 'capacity', 'FANTASY', 414);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Until the End of the World (Bis ans Ende der Welt)', 17, 45, 33828, 'open architecture', 'THRILLER', 324);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Lone Wolf and Cub: Baby Cart in the Land of Demons (Kozure Ôkami: Meifumadô)', 497, 56, 26756, 'benchmark', 'FANTASY', 225);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Alice Doesn''t Live Here Anymore', 266, 22, 4872, 'global', 'TRAGEDY', 429);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Low Life', 116, 98, 15937, 'extranet', 'FANTASY', 384);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('My Mother (Ma mère)', 372, 24, 7601, 'explicit', 'WESTERN', 251);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Desperate', 438, 92, 17503, 'uniform', 'TRAGEDY', 493);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Yanco ', 302, 62, 5659, 'background', 'THRILLER', 420);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('The Pacific', 305, 18, 27756, 'Persistent', 'WESTERN', 232);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Lovesick', 450, 60, 16288, 'methodical', 'TRAGEDY', 89);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Heart of Dragon (Long de xin)', 6, 24, 17812, 'Open-source', 'DRAMA', 316);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Hamlet', 76, 26, 20458, 'function', 'DRAMA', 311);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Conceiving Ada', 56, 34, 3705, 'zero administration', 'TRAGEDY', 435);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Semi-Tough', 50, 0, 4241, 'solution', 'WESTERN', 393);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Long John Silver', 327, 83, 27774, 'optimizing', 'TRAGEDY', 197);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Flow: For Love of Water', 98, 58, 21468, 'Expanded', 'DRAMA', 4);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Rouge (Yin ji kau)', 177, 81, 14492, 'fault-tolerant', 'WESTERN', 291);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Reality', 231, 31, 6282, 'protocol', 'TRAGEDY', 470);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Tycoon', 411, 21, 24189, 'support', 'DRAMA', 426);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Sunflower (Xiang ri kui)', 488, 1, 9109, 'analyzing', 'WESTERN', 54);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('At Sword''s Point', 223, 22, 21541, 'Exclusive', 'DRAMA', 248);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Beast Must Die, The', 215, 20, 19546, 'leading edge', 'DRAMA', 96);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Jack Frost', 407, 82, 34957, 'throughput', 'TRAGEDY', 152);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Magdalene Sisters, The', 215, 22, 30402, 'multi-state', 'DRAMA', 18);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Holy Man, The (Mahapurush)', 402, 89, 25400, 'service-desk', 'DRAMA', 50);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Client 9: The Rise and Fall of Eliot Spitzer', 124, 95, 8132, 'Stand-alone', 'FANTASY', 441);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('All Mine to Give', 476, 91, 1968, '24/7', 'FANTASY', 183);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Where Were You When the Lights Went Out?', 328, 58, 27841, 'Optimized', 'TRAGEDY', 416);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Cruise, The', 270, 93, 7860, 'Versatile', 'THRILLER', 128);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Heaven & Earth', 496, 94, 24050, 'Quality-focused', 'DRAMA', 103);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('West of the Divide', 40, 49, 28786, 'asynchronous', 'DRAMA', 171);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Kings Row', 419, 33, 2437, 'object-oriented', 'THRILLER', 287);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('House of the Seven Gables, The', 150, 8, 10116, 'Mandatory', 'THRILLER', 484);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Enigma', 414, 35, 19413, 'intermediate', 'FANTASY', 175);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Innerspace', 379, 95, 23043, 'Centralized', 'TRAGEDY', 458);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Air America', 103, 96, 33528, 'exuding', 'THRILLER', 272);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Red Sonja', 347, 16, 16302, 'Enhanced', 'FANTASY', 479);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('First Man Into Space', 191, 73, 27087, 'contingency', 'TRAGEDY', 250);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Secret Honor', 220, 63, 14369, 'fresh-thinking', 'FANTASY', 281);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('I Am Michael', 91, 37, 19945, 'object-oriented', 'DRAMA', 397);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Target Shoots First, The', 443, 30, 13986, 'database', 'FANTASY', 393);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Lower Depths, The (Donzoko)', 102, 80, 21920, 'hierarchy', 'DRAMA', 474);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Little White Lies (Les petits mouchoirs)', 314, 17, 33656, 'approach', 'DRAMA', 134);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Music Man, The', 65, 42, 19739, 'Enhanced', 'FANTASY', 268);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Spy Who Loved Me, The', 365, 61, 9843, 'paradigm', 'WESTERN', 155);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Wee Willie Winkie', 275, 39, 26320, 'Ergonomic', 'THRILLER', 24);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('First Day of the Rest of Your Life, The (Le premier jour du reste de ta vie)', 473, 18, 27144, 'orchestration', 'WESTERN', 366);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Mr. Moto in Danger Island', 469, 42, 32465, 'framework', 'DRAMA', 419);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('a/k/a Tommy Chong', 190, 84, 25987, 'encoding', 'TRAGEDY', 456);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Coming Down the Mountain', 465, 12, 12638, 'optimal', 'WESTERN', 257);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Stockholm Stories', 278, 16, 5631, 'Secured', 'DRAMA', 380);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Ferngully: The Last Rainforest', 426, 80, 8175, 'cohesive', 'TRAGEDY', 441);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Night Moves', 449, 66, 10526, 'Right-sized', 'DRAMA', 325);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Lovers, The (Les Amants)', 230, 76, 29509, 'system-worthy', 'WESTERN', 229);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Strawberry Wine', 287, 73, 7239, 'knowledge user', 'DRAMA', 381);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Wooden Crosses (Les croix de bois)', 149, 37, 14381, 'time-frame', 'TRAGEDY', 411);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Luv', 471, 46, 20649, 'Organic', 'DRAMA', 491);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Polskie gówno', 78, 42, 25830, 'User-friendly', 'FANTASY', 177);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Firstborn', 29, 19, 14758, 'secondary', 'DRAMA', 496);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Healing', 372, 37, 25120, 'firmware', 'FANTASY', 250);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Bottom of the Sea, The (El fondo del mar)', 67, 58, 23971, 'heuristic', 'FANTASY', 401);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Plenty', 19, 94, 2397, 'Cross-group', 'DRAMA', 333);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Soupe aux Choux, La', 155, 33, 30413, 'Phased', 'FANTASY', 490);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Raising Helen', 196, 80, 34406, 'directional', 'FANTASY', 469);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Underneath', 415, 86, 7465, 'Centralized', 'FANTASY', 8);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Incubus', 478, 82, 29087, 'instruction set', 'FANTASY', 341);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Watch on the Rhine', 284, 12, 9730, 'protocol', 'DRAMA', 194);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Kill Me Again', 105, 20, 26397, 'Open-architected', 'THRILLER', 100);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Shall We Dance?', 77, 26, 8752, 'Devolved', 'DRAMA', 262);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Babes on Broadway', 197, 71, 13841, 'core', 'FANTASY', 40);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Stalker', 36, 46, 28610, '24/7', 'TRAGEDY', 237);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Curse of the Hedgehog, The (Blestemul ariciului)', 231, 94, 13925, 'Compatible', 'FANTASY', 203);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('That''s Entertainment', 329, 48, 26206, 'Configurable', 'DRAMA', 400);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Conquest 1453 (Fetih 1453)', 453, 99, 26715, 'Public-key', 'TRAGEDY', 250);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('So Much Water', 344, 75, 27804, 'Multi-channelled', 'TRAGEDY', 438);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Otis', 267, 57, 22823, 'frame', 'THRILLER', 359);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Follow That Dream', 351, 83, 28019, 'Pre-emptive', 'DRAMA', 213);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Delicate Delinquent, The', 358, 96, 12676, 'Team-oriented', 'WESTERN', 466);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Giliap', 385, 78, 33243, 'analyzer', 'WESTERN', 224);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Short Sharp Shock (Kurz und schmerzlos) ', 346, 10, 34097, 'Optional', 'TRAGEDY', 337);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Santa Claus: The Movie', 159, 48, 24920, 'matrices', 'DRAMA', 159);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Event Horizon', 111, 19, 13322, 'Progressive', 'TRAGEDY', 223);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('President''s Man, The', 430, 37, 34559, 'hierarchy', 'FANTASY', 365);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Hope Springs', 334, 73, 1177, 'Robust', 'TRAGEDY', 191);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('49th Parallel', 382, 25, 3250, 'Graphical User Interface', 'THRILLER', 2);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Siberia', 70, 62, 11501, 'intranet', 'THRILLER', 62);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Strangers When We Meet', 426, 18, 32423, 'Multi-tiered', 'WESTERN', 2);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Dick Tracy', 410, 0, 16913, 'Total', 'FANTASY', 390);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('American Son', 322, 94, 13541, 'Multi-channelled', 'FANTASY', 138);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Into the Deep', 469, 11, 28355, 'even-keeled', 'TRAGEDY', 427);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Stonewall', 319, 94, 10219, 'Progressive', 'DRAMA', 37);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Different from You and Me (Anders als du und ich) ', 381, 31, 34410, 'discrete', 'WESTERN', 219);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Signs', 192, 15, 34312, 'zero defect', 'TRAGEDY', 180);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Girl of Finland (Lapualaismorsian)', 235, 69, 8537, 'empowering', 'THRILLER', 2);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Never Ever! (Nigdy w zyciu!)', 116, 86, 16035, 'maximized', 'TRAGEDY', 246);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Godzilla, King of the Monsters! (Kaijû-ô Gojira)', 184, 12, 16796, 'fresh-thinking', 'TRAGEDY', 361);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('My Bloody Valentine 3-D', 270, 96, 3608, 'knowledge base', 'WESTERN', 495);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Exit', 452, 36, 10623, 'multi-tasking', 'TRAGEDY', 140);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Undefeated, The', 400, 97, 19436, 'Quality-focused', 'DRAMA', 455);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('And the Pursuit of Happiness (La poursuite du bonheur)', 409, 89, 22638, 'well-modulated', 'WESTERN', 458);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Knights of the Round Table', 282, 7, 9651, 'encompassing', 'THRILLER', 48);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Never Ever! (Nigdy w zyciu!)', 346, 56, 11164, 'conglomeration', 'THRILLER', 193);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('13th Warrior, The', 467, 94, 15789, 'Managed', 'THRILLER', 441);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Million Dollar Baby', 441, 44, 10161, 'zero administration', 'FANTASY', 154);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Rude Boy', 406, 51, 5920, 'Cross-group', 'FANTASY', 63);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Die, Monster, Die!', 312, 29, 13352, 'Advanced', 'TRAGEDY', 424);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Waking Sleeping Beauty', 359, 53, 1934, 'moratorium', 'DRAMA', 402);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Welcome to the Sticks (Bienvenue chez les Ch''tis)', 112, 44, 12900, 'Ergonomic', 'THRILLER', 202);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Green Fire', 111, 76, 2909, 'Upgradable', 'THRILLER', 298);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Into the Storm', 462, 87, 8954, 'attitude', 'TRAGEDY', 383);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Someone''s Watching Me!', 244, 41, 34312, 'capability', 'THRILLER', 495);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Soul Plane', 419, 77, 31042, 'leverage', 'FANTASY', 400);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Blair Witch Project, The', 358, 75, 31255, 'artificial intelligence', 'TRAGEDY', 236);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Big Man Japan (Dai-Nihonjin)', 159, 33, 19879, 'internet solution', 'FANTASY', 437);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Where Sleeping Dogs Lie', 471, 36, 11161, 'Seamless', 'TRAGEDY', 158);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Dead Man Walking', 174, 7, 10486, 'clear-thinking', 'FANTASY', 335);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('I Saw Mommy Kissing Santa Claus', 288, 1, 24166, 'workforce', 'TRAGEDY', 299);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Bloodtide', 240, 26, 10472, 'Function-based', 'THRILLER', 121);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('House of Strangers', 274, 48, 32905, 'alliance', 'FANTASY', 196);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Greatest Love, The (Europa ''51)', 458, 79, 2360, 'installation', 'WESTERN', 398);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Walk of Shame', 1, 74, 33154, 'exuding', 'TRAGEDY', 459);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Funny Face', 204, 54, 29874, 'benchmark', 'WESTERN', 376);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('16 to Life', 393, 65, 31895, 'standardization', 'THRILLER', 194);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Hunters, The (Jägarna)', 429, 95, 31212, 'process improvement', 'WESTERN', 485);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Mosquito Net, The (La mosquitera)', 337, 24, 6270, 'upward-trending', 'DRAMA', 426);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('What''s Up, Scarlet?', 122, 49, 25071, 'Up-sized', 'TRAGEDY', 32);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Horse''s Mouth, The', 22, 39, 12021, 'architecture', 'WESTERN', 417);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('The (Dead Mothers) Club', 227, 20, 30798, 'Monitored', 'FANTASY', 234);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Those Magnificent Men in Their Flying Machines', 444, 93, 19841, 'methodical', 'TRAGEDY', 495);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Burn, Witch, Burn (Night of the Eagle)', 109, 46, 15849, 'architecture', 'DRAMA', 450);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Monsterman (Monsterimies)', 43, 22, 20729, 'utilisation', 'DRAMA', 427);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Elmer Gantry', 457, 29, 34787, 'local', 'FANTASY', 124);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Vanishing Point', 1, 57, 20310, 'asynchronous', 'TRAGEDY', 448);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Blindsight', 191, 3, 9252, 'Networked', 'THRILLER', 236);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Missing in Action', 355, 36, 7957, 'Configurable', 'WESTERN', 443);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Caddyshack II', 186, 23, 20353, 'Progressive', 'WESTERN', 385);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Fright Night', 314, 79, 5401, 'hardware', 'DRAMA', 478);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Bad Guy (Nabbeun namja)', 162, 28, 6056, 'Cross-group', 'WESTERN', 107);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Jive Turkey', 341, 16, 26381, 'Implemented', 'WESTERN', 243);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Gate, The', 27, 21, 33450, '5th generation', 'FANTASY', 151);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('iSteve', 240, 9, 1522, 'strategy', 'FANTASY', 184);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Dying at Grace', 175, 6, 33547, 'Devolved', 'DRAMA', 337);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Manchurian Candidate, The', 21, 75, 2112, 'hierarchy', 'WESTERN', 242);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Red Baron, The (Der rote Baron)', 228, 100, 9490, 'groupware', 'TRAGEDY', 395);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('6 Bullets', 193, 94, 3343, 'uniform', 'WESTERN', 144);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('What Have I Done to Deserve This? (¿Qué he hecho yo para merecer esto!!)', 470, 47, 15027, 'motivating', 'DRAMA', 168);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Return of Jafar, The', 376, 32, 34215, 'reciprocal', 'TRAGEDY', 52);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Hellion', 442, 100, 14394, 'holistic', 'WESTERN', 499);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Gift, The', 498, 50, 7861, 'Adaptive', 'WESTERN', 233);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Starving Games, The', 97, 99, 529, 'Multi-channelled', 'FANTASY', 172);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('The Good Son', 345, 98, 18171, 'Distributed', 'TRAGEDY', 67);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Premonition', 345, 21, 31432, 'matrices', 'FANTASY', 121);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Touch of Evil', 9, 6, 33434, 'Horizontal', 'TRAGEDY', 460);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Spring Breakdown', 85, 74, 34334, 'didactic', 'TRAGEDY', 477);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Grey Gardens', 179, 9, 32986, 'real-time', 'WESTERN', 366);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Ballad of Ramblin'' Jack, The', 33, 21, 8509, 'interactive', 'DRAMA', 117);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('OMG Oh My God!', 346, 21, 4540, 'even-keeled', 'TRAGEDY', 71);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Walk Softly, Stranger', 300, 88, 15960, 'intranet', 'THRILLER', 286);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Suture', 186, 26, 1567, 'Triple-buffered', 'DRAMA', 442);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Five', 294, 0, 5231, 'leading edge', 'DRAMA', 252);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Unstoppable', 160, 20, 4222, 'firmware', 'WESTERN', 33);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Stranger, The (Agantuk) (Visitor, The)', 47, 61, 3291, 'tertiary', 'THRILLER', 195);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('How the Grinch Stole Christmas (a.k.a. The Grinch)', 409, 23, 25076, 'disintermediate', 'DRAMA', 481);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Purpose', 421, 68, 30939, 'Visionary', 'THRILLER', 178);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Main Street', 320, 21, 2626, 'website', 'DRAMA', 248);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Who Killed Vincent Chin?', 496, 68, 32910, 'radical', 'THRILLER', 28);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('13 Frightened Girls! (Candy Web, The)', 161, 47, 10896, 'model', 'THRILLER', 236);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Cars 2', 316, 52, 17268, 'Profit-focused', 'WESTERN', 88);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Animal, The', 492, 71, 30424, 'artificial intelligence', 'FANTASY', 378);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Maya Lin: A Strong Clear Vision', 76, 21, 22331, 'multimedia', 'WESTERN', 254);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('It Is Written in the Stars, Inspector Palmu (Tähdet kertovat, komisario Palmu)', 253, 31, 20541, '5th generation', 'WESTERN', 472);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('President''s Man: A Line in the Sand, The', 357, 22, 13708, 'Switchable', 'TRAGEDY', 390);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Man-Thing', 309, 96, 2034, 'Mandatory', 'DRAMA', 136);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Centenarian Who Climbed Out the Window and Vanished, The (Hundraåringen som klev ut genom fönstret och försvann)', 431, 37, 18381, 'capacity', 'DRAMA', 120);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('In a World...', 435, 99, 21639, 'adapter', 'TRAGEDY', 93);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Monkey''s Teeth (Dents du singe, Les)', 194, 71, 9839, 'secured line', 'TRAGEDY', 181);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Korso', 301, 92, 27874, 'flexibility', 'FANTASY', 284);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Cannonball', 447, 76, 13030, 'bifurcated', 'WESTERN', 114);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Road to Rio', 356, 19, 6232, 'even-keeled', 'THRILLER', 127);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Night of the Comet', 289, 81, 10426, 'artificial intelligence', 'DRAMA', 448);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Secret Policeman''s Other Ball, The', 374, 60, 12853, 'Synchronised', 'THRILLER', 161);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Nanny Diaries, The', 284, 51, 20170, 'algorithm', 'THRILLER', 494);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Welcome to Macintosh', 135, 83, 28031, 'database', 'DRAMA', 10);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Easy Life, The (Il Sorpasso)', 216, 74, 2846, 'capability', 'FANTASY', 489);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Marriage Made in Heaven, A (Rab Ne Bana Di Jodi)', 377, 26, 6746, 'productivity', 'THRILLER', 404);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Merantau', 484, 42, 18122, 'Fully-configurable', 'WESTERN', 97);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Carnegie Hall', 244, 46, 7725, 'Inverse', 'TRAGEDY', 262);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Circles (Krugovi)', 332, 24, 18159, 'holistic', 'WESTERN', 290);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Final Darkness, The (Buio Omega)', 383, 53, 12429, 'foreground', 'FANTASY', 67);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Material Girls', 352, 24, 25228, 'methodical', 'DRAMA', 210);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Black Field', 364, 25, 28881, 'zero defect', 'WESTERN', 71);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Lawless Breed, The', 369, 16, 27123, 'composite', 'WESTERN', 347);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Normal', 105, 23, 12147, 'Fully-configurable', 'TRAGEDY', 179);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Hunting Party, The', 175, 97, 654, 'human-resource', 'THRILLER', 415);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Fortress', 444, 23, 20510, 'Reverse-engineered', 'TRAGEDY', 445);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Drop, The', 167, 45, 7049, 'Total', 'THRILLER', 494);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Hangmen Also Die', 233, 40, 9004, '3rd generation', 'THRILLER', 475);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Hannah Free', 393, 41, 6368, 'background', 'DRAMA', 416);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Cross: The Arthur Blessitt Story, The', 65, 42, 11068, 'background', 'THRILLER', 405);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('When Evening Falls on Bucharest or Metabolism', 328, 80, 19994, 'motivating', 'TRAGEDY', 221);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Confession', 91, 62, 7134, 'Down-sized', 'FANTASY', 362);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Wanda Sykes: Sick and Tired', 25, 7, 1870, 'Intuitive', 'FANTASY', 476);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Down to Earth', 487, 36, 5168, 'bifurcated', 'FANTASY', 14);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Lola Versus', 472, 92, 3222, 'bifurcated', 'THRILLER', 356);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Happily Ever After (Ils se marièrent et eurent beaucoup d''enfants)', 359, 54, 12, 'even-keeled', 'TRAGEDY', 403);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Main Event, The', 219, 5, 27032, 'exuding', 'WESTERN', 57);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('See You Tomorrow, Everyone', 386, 16, 591, 'artificial intelligence', 'TRAGEDY', 21);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Exorcist: The Beginning', 453, 58, 33865, 'Public-key', 'THRILLER', 176);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Mirror, The (Ayneh)', 105, 89, 12783, 'Face to face', 'DRAMA', 414);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('The Kingdom of Dreams and Madness', 350, 90, 15799, 'analyzing', 'WESTERN', 284);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Ocean''s Eleven', 157, 38, 419, 'coherent', 'DRAMA', 478);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('GasLand', 216, 49, 2769, 'frame', 'THRILLER', 372);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Dust Devil', 12, 61, 21921, 'background', 'WESTERN', 246);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Looker', 400, 56, 23610, 'human-resource', 'DRAMA', 234);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Katsastus', 133, 38, 10198, 'Right-sized', 'TRAGEDY', 173);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Girl Next Door, The', 125, 29, 14472, 'client-server', 'WESTERN', 202);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Fire on the Mountain', 284, 42, 2633, 'Proactive', 'WESTERN', 281);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Of Mice and Men', 36, 97, 27715, 'Synchronised', 'WESTERN', 459);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Monsters vs Aliens: Mutant Pumpkins from Outer Space', 224, 7, 4486, 'Total', 'TRAGEDY', 454);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Clockmaker of St. Paul, The (L''horloger de Saint-Paul)', 31, 41, 27853, 'moratorium', 'FANTASY', 223);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Reeds, The', 442, 89, 13751, 'De-engineered', 'TRAGEDY', 252);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Crossroads', 111, 72, 28950, 'De-engineered', 'WESTERN', 238);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Journey for Margaret', 112, 33, 11138, 'alliance', 'FANTASY', 59);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Film ist a Girl & a Gun', 452, 33, 2149, 'Up-sized', 'DRAMA', 42);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Red Elvis, The (Der rote Elvis)', 133, 73, 2295, 'heuristic', 'WESTERN', 45);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Consenting Adults', 177, 23, 33698, 'middleware', 'TRAGEDY', 251);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Terminator 2: Judgment Day', 310, 27, 6576, 'scalable', 'TRAGEDY', 30);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Brazilian Western (Faroeste Caboclo)', 460, 35, 21280, 'optimal', 'THRILLER', 25);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('13 Rue Madeleine', 121, 52, 34411, 'Profound', 'WESTERN', 47);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Rated X: A Journey Through Porn', 232, 62, 33243, 'next generation', 'FANTASY', 101);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Faces of Death 3', 44, 45, 16963, 'Advanced', 'FANTASY', 72);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Tell-Tale', 67, 1, 17075, 'Reduced', 'FANTASY', 318);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('It''s Alive III: Island of the Alive', 292, 29, 27167, 'website', 'THRILLER', 270);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('And When Did You Last See Your Father?', 329, 43, 2753, 'moderator', 'TRAGEDY', 28);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Sholay', 97, 86, 5041, 'Universal', 'DRAMA', 59);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('London After Midnight', 430, 63, 33813, 'Triple-buffered', 'FANTASY', 198);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('MacGyver: Lost Treasure of Atlantis', 124, 92, 9772, 'hub', 'THRILLER', 253);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Rebel, The (Le Rebelle)', 20, 72, 12993, 'dynamic', 'TRAGEDY', 69);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('EDtv', 297, 82, 33298, 'Centralized', 'THRILLER', 320);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Directed by John Ford', 445, 46, 12470, 'empowering', 'FANTASY', 464);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Erik the Viking', 378, 15, 29021, 'strategy', 'DRAMA', 392);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Judgment at Nuremberg', 359, 3, 7918, 'Grass-roots', 'THRILLER', 333);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Phil Spector', 280, 4, 3040, 'static', 'WESTERN', 260);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Slams, The', 248, 51, 29613, 'exuding', 'FANTASY', 425);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('California', 292, 31, 33858, 'zero defect', 'FANTASY', 357);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Fool There Was, A', 241, 90, 18630, 'Re-contextualized', 'DRAMA', 78);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Homer & Eddie', 18, 85, 31234, 'Operative', 'FANTASY', 45);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Prelude to a Kiss', 342, 11, 33492, 'Grass-roots', 'THRILLER', 114);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('I Can''t Sleep (J''ai pas sommeil)', 243, 100, 18921, 'bandwidth-monitored', 'TRAGEDY', 302);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('You Are So Beautiful (Je vous trouve très beau)', 239, 34, 26135, 'Sharable', 'THRILLER', 406);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Man Who Planted Trees, The (Homme qui plantait des arbres, L'')', 313, 21, 30554, 'Secured', 'DRAMA', 267);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Thunderbolt and Lightfoot', 417, 38, 6484, 'Operative', 'DRAMA', 428);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Bridge at Remagen, The', 120, 2, 6606, 'Future-proofed', 'DRAMA', 376);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('The Gold Spinners', 436, 2, 30416, 'Proactive', 'THRILLER', 366);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Jolene', 207, 68, 26939, 'Optimized', 'WESTERN', 449);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Two for the Seesaw', 46, 49, 9306, 'upward-trending', 'THRILLER', 285);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Drei Stunden', 426, 9, 7740, 'homogeneous', 'WESTERN', 21);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Wallace and Gromit in ''A Matter of Loaf and Death''', 328, 43, 34792, 'Devolved', 'WESTERN', 462);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Signs of Life (Lebenszeichen)', 170, 56, 22581, 'Decentralized', 'TRAGEDY', 324);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Twilight Samurai, The (Tasogare Seibei)', 237, 91, 3773, 'didactic', 'WESTERN', 152);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Food of the Gods II', 300, 93, 18339, 'Digitized', 'DRAMA', 71);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Kissed by Winter (Vinterkyss)', 463, 53, 11802, 'knowledge user', 'TRAGEDY', 19);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Lauderdale (a.k.a. Spring Break USA) (a.k.a. Spring Fever USA)', 260, 69, 11893, 'productivity', 'TRAGEDY', 17);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Broken English', 382, 26, 14836, 'tertiary', 'FANTASY', 35);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Half Moon (a.k.a. Niwemang)', 305, 33, 5701, 'directional', 'FANTASY', 90);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Miss Sadie Thompson', 356, 17, 20293, 'Object-based', 'DRAMA', 364);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Command Decision', 159, 96, 4082, 'architecture', 'THRILLER', 111);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Crazy in Alabama', 334, 87, 33431, 'grid-enabled', 'FANTASY', 362);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Runaway Jury', 401, 24, 30095, 'needs-based', 'TRAGEDY', 344);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Soft Fruit', 227, 10, 14163, 'neutral', 'WESTERN', 358);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Bitter Sugar (Azúcar amarga)', 493, 80, 10554, 'didactic', 'WESTERN', 318);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Audition (Ôdishon)', 479, 97, 31373, 'website', 'THRILLER', 183);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Con Air', 77, 5, 24175, 'bottom-line', 'THRILLER', 333);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Charlie Chan in Egypt', 416, 75, 23183, 'Decentralized', 'FANTASY', 320);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Secrets, The (Sodot, Ha-)', 2, 66, 2724, 'bi-directional', 'WESTERN', 360);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('The Casino Murder Case', 227, 53, 11471, 'stable', 'FANTASY', 228);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Billy Jack Goes to Washington', 248, 78, 16746, 'systemic', 'TRAGEDY', 173);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Code Conspiracy, The', 438, 69, 20639, 'Distributed', 'WESTERN', 389);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Junior Bonner', 148, 77, 25434, 'projection', 'WESTERN', 447);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Baby-Sitters Club, The', 221, 88, 25856, 'dynamic', 'THRILLER', 160);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Brief Vacation, A (breve vacanza, Una)', 409, 20, 14255, 'object-oriented', 'FANTASY', 115);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Cop', 34, 58, 27799, 'contingency', 'WESTERN', 330);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Sex Ed', 226, 94, 5238, 'frame', 'WESTERN', 133);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('We Are Marshall', 499, 73, 2983, '24 hour', 'TRAGEDY', 93);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Ladies They Talk About', 305, 48, 28688, 'methodical', 'FANTASY', 420);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Undefeated, The', 191, 75, 25610, 'Cross-group', 'WESTERN', 36);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Buud Yam', 108, 21, 15262, 'Re-engineered', 'FANTASY', 180);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('How Stella Got Her Groove Back', 83, 7, 14513, 'Re-engineered', 'THRILLER', 275);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Rosario Tijeras', 195, 95, 26218, 'clear-thinking', 'WESTERN', 318);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Payback', 133, 75, 24599, 'Polarised', 'THRILLER', 250);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Perez Family, The', 364, 51, 15278, 'regional', 'TRAGEDY', 79);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Cimarron Kid, The', 358, 95, 31142, 'Sharable', 'WESTERN', 498);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Katy Perry: Part of Me', 45, 16, 34478, 'structure', 'THRILLER', 295);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Blue Steel', 221, 36, 18846, 'architecture', 'DRAMA', 448);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Hollywood Shuffle', 395, 49, 32663, '3rd generation', 'FANTASY', 122);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Assisted Living', 154, 92, 28880, 'eco-centric', 'DRAMA', 347);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Get Yourself a College Girl', 143, 0, 5769, 'artificial intelligence', 'FANTASY', 338);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Hideous Kinky', 355, 90, 10692, 'Sharable', 'FANTASY', 173);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Girl of Finland (Lapualaismorsian)', 420, 33, 793, 'Synchronised', 'TRAGEDY', 176);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Butterflies Have No Memories', 378, 67, 18425, 'Enterprise-wide', 'THRILLER', 234);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Romeo and Juliet', 334, 59, 27297, 'cohesive', 'DRAMA', 35);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Guilty Hands', 60, 48, 11691, 'contingency', 'DRAMA', 2);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Hatfields & McCoys', 237, 70, 11324, 'Graphic Interface', 'THRILLER', 32);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Dead Silence', 39, 15, 28331, 'Expanded', 'THRILLER', 244);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Fifth Cord, The (Giornata nera per l''ariete)', 328, 54, 10271, 'systematic', 'THRILLER', 334);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('3 Penny Opera, The (Threepenny Opera, The) (3 Groschen-Oper, Die)', 361, 22, 18137, 'demand-driven', 'DRAMA', 485);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Bedtime Stories', 437, 90, 8875, 'directional', 'TRAGEDY', 324);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Woman Obsessed', 190, 2, 14091, 'asymmetric', 'TRAGEDY', 217);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Loneliest Planet, The', 268, 95, 5341, 'upward-trending', 'WESTERN', 462);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Happy Times (Xingfu shiguang)', 318, 39, 12807, 'multimedia', 'DRAMA', 153);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('International, The', 302, 64, 20976, 'Virtual', 'WESTERN', 238);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Union Station', 44, 17, 142, 'Extended', 'DRAMA', 9);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Party, The (Boum, La)', 243, 97, 449, 'Object-based', 'WESTERN', 235);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Red Beret, The', 407, 34, 14947, 'holistic', 'FANTASY', 412);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Deserter (Dezertir)', 482, 48, 14292, 'User-centric', 'FANTASY', 448);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Beautiful', 280, 39, 6064, 'installation', 'WESTERN', 277);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Spellbound', 162, 10, 11780, 'frame', 'THRILLER', 169);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('A Grain of Truth', 466, 16, 31034, 'Persevering', 'WESTERN', 163);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Return of the Vampire, The', 390, 27, 33930, 'national', 'FANTASY', 96);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Anna and the King of Siam', 114, 52, 5624, 'content-based', 'WESTERN', 103);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('One Bright Shining Moment', 248, 87, 34898, 'system engine', 'TRAGEDY', 174);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('The Body', 62, 25, 11460, 'Monitored', 'TRAGEDY', 191);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Straightheads (Closure)', 256, 96, 26562, 'Cross-group', 'TRAGEDY', 83);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Blues Harp', 420, 41, 17219, 'even-keeled', 'THRILLER', 475);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Study in Choreography for Camera, A', 215, 31, 2130, 'model', 'THRILLER', 150);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Setup (Set Up)', 444, 51, 10180, 'Enhanced', 'THRILLER', 84);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Project Wild Thing', 482, 62, 10067, 'neural-net', 'WESTERN', 4);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Between Miracles', 58, 98, 30635, 'Organized', 'FANTASY', 474);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Ah of Life, The', 138, 53, 2332, 'Compatible', 'FANTASY', 95);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('10', 38, 87, 10463, 'orchestration', 'WESTERN', 234);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Most Hated Family in America, The', 227, 23, 21754, 'Streamlined', 'WESTERN', 289);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Shanghai Surprise', 70, 32, 32399, 'Streamlined', 'FANTASY', 417);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Let the Bullets Fly', 6, 9, 19161, 'executive', 'THRILLER', 426);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Rock & Rule', 17, 24, 2608, 'Pre-emptive', 'FANTASY', 8);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Master of Ballantrae, The', 348, 70, 2809, 'Multi-channelled', 'THRILLER', 414);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Thomas Jefferson', 256, 68, 28205, 'Team-oriented', 'WESTERN', 136);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('North by Northwest', 121, 41, 20992, 'core', 'FANTASY', 153);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('22 Bullets (L''immortel)', 150, 92, 4909, 'Programmable', 'DRAMA', 165);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Otis', 16, 89, 22231, 'Reactive', 'TRAGEDY', 463);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Castle on the Hudson', 154, 89, 26821, 'local area network', 'DRAMA', 115);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Crawling Hand, The', 118, 18, 2554, 'Digitized', 'FANTASY', 483);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('She Wouldn''t Say Yes', 497, 55, 4612, 'Enhanced', 'DRAMA', 156);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Nokas', 379, 66, 312, 'actuating', 'TRAGEDY', 432);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Experimenter', 404, 97, 11789, 'ability', 'TRAGEDY', 165);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Thumbelina', 161, 89, 9159, 'asymmetric', 'THRILLER', 447);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Adjustment Bureau, The', 306, 6, 2132, 'non-volatile', 'FANTASY', 302);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('The Opposite Sex', 433, 78, 2422, '6th generation', 'FANTASY', 411);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Robots', 373, 10, 27348, 'strategy', 'WESTERN', 245);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Fudoh: The New Generation (Gokudô sengokushi: Fudô)', 129, 43, 30334, 'Pre-emptive', 'FANTASY', 110);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Bright Lights, Big City', 252, 64, 9012, 'service-desk', 'TRAGEDY', 365);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Commune, La (Paris, 1871)', 423, 45, 29647, 'standardization', 'FANTASY', 283);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Benny Goodman Story, The', 285, 69, 8689, 'dedicated', 'WESTERN', 424);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Ciel est à vous, Le (Woman Who Dared, The)', 163, 17, 14165, 'forecast', 'THRILLER', 42);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Wanda', 20, 0, 22089, 'methodical', 'WESTERN', 430);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Attraction', 59, 15, 25643, 'Focused', 'FANTASY', 312);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Charlie Brown''s Christmas Tales', 220, 89, 24989, 'intangible', 'WESTERN', 220);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Furry Vengeance', 128, 61, 32477, 'impactful', 'FANTASY', 4);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Moment of Truth, The (Il momento della verità)', 489, 12, 5496, 'methodical', 'DRAMA', 241);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Titanic', 399, 86, 18006, 'context-sensitive', 'FANTASY', 424);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Foo Fighters: Back and Forth', 210, 58, 23083, 'software', 'THRILLER', 223);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Irene in Time', 346, 25, 12988, 'support', 'FANTASY', 185);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Trailer Park Boys: Countdown to Liquor Day', 469, 67, 26407, 'clear-thinking', 'DRAMA', 293);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('SpongeBob Movie: Sponge Out of Water, The', 19, 45, 16889, 'Proactive', 'DRAMA', 119);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Undiscovered', 330, 16, 21542, 'architecture', 'WESTERN', 363);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Ill Manors', 116, 89, 12390, 'Inverse', 'WESTERN', 307);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('X-Men', 489, 89, 26629, 'systematic', 'TRAGEDY', 5);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('From the Sky Down', 283, 87, 5418, 'internet solution', 'WESTERN', 481);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Dark Horse, The', 398, 3, 24298, 'national', 'FANTASY', 91);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Cheat, The', 331, 54, 28335, 'national', 'WESTERN', 489);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Amelia', 410, 99, 507, 'Phased', 'THRILLER', 291);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Taxi 3', 308, 96, 1347, 'Total', 'TRAGEDY', 146);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Arrowsmith', 5, 79, 19525, 'Graphical User Interface', 'TRAGEDY', 210);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Red Lights (Feux rouges)', 416, 73, 17253, 'Cloned', 'TRAGEDY', 301);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Sublime', 420, 19, 20492, 'support', 'FANTASY', 10);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Great Communist Bank Robbery (Marele jaf comunist)', 134, 8, 16833, 'architecture', 'FANTASY', 385);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Relative Fear', 378, 81, 7413, 'Switchable', 'DRAMA', 246);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Asylum', 240, 8, 15351, 'Right-sized', 'THRILLER', 147);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('You''re Gonna Miss Me', 228, 84, 30572, 'real-time', 'DRAMA', 398);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Runaways, The', 171, 67, 14427, 'Graphic Interface', 'TRAGEDY', 383);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Wind Journeys, The (Viajes del viento, Los)', 124, 36, 28624, 'Intuitive', 'TRAGEDY', 500);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Fuel', 25, 78, 4998, 'Realigned', 'DRAMA', 422);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Walking with Monsters', 257, 57, 971, 'executive', 'DRAMA', 129);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Female', 404, 15, 32310, 'maximized', 'DRAMA', 379);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('The Nutcracker in 3D', 248, 59, 13538, 'analyzer', 'THRILLER', 172);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Miranda', 249, 80, 3980, 'policy', 'THRILLER', 73);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Libre échange', 336, 54, 23380, 'systemic', 'TRAGEDY', 64);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Joni''s Promise', 328, 80, 29053, 'Customizable', 'TRAGEDY', 278);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Slam Dunk Ernest', 491, 75, 9827, 'product', 'THRILLER', 212);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Man with the Movie Camera, The (Chelovek s kino-apparatom)', 397, 17, 21672, 'real-time', 'DRAMA', 424);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Volver', 186, 70, 3375, 'Phased', 'TRAGEDY', 465);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Rich and Famous (Gong woo ching)', 499, 43, 13813, 'Innovative', 'FANTASY', 57);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Raiders of Atlantis, The', 382, 76, 30926, 'implementation', 'TRAGEDY', 99);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('History Is Made at Night', 138, 1, 34224, 'matrices', 'TRAGEDY', 143);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Goddess (Devi)', 125, 40, 25158, 'radical', 'WESTERN', 305);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Lucky One, The', 128, 87, 15891, 'Multi-tiered', 'DRAMA', 184);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Dillinger', 32, 54, 30944, 'Visionary', 'DRAMA', 356);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Caddyshack II', 119, 31, 16883, 'support', 'THRILLER', 39);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Caine Mutiny Court-Martial, The', 60, 54, 9279, 'optimal', 'WESTERN', 452);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Bugs Bunny''s Looney Christmas Tales', 116, 1, 14785, 'multimedia', 'TRAGEDY', 384);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Busting', 448, 87, 287, 'portal', 'TRAGEDY', 147);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Mass Appeal', 426, 92, 26504, 'User-friendly', 'THRILLER', 46);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('You Don''t Know Jack', 270, 39, 8651, 'needs-based', 'THRILLER', 431);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Chuck & Buck', 488, 45, 18074, 'Front-line', 'DRAMA', 294);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Blob, The', 240, 18, 31182, 'capacity', 'FANTASY', 341);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Temp, The', 100, 27, 16892, 'zero defect', 'FANTASY', 427);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('For Me and My Gal', 322, 12, 20281, 'website', 'DRAMA', 69);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Decoding Annie Parker', 318, 78, 28489, 'interface', 'DRAMA', 121);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Murder on a Sunday Morning (Un coupable idéal)', 427, 44, 34179, 'holistic', 'TRAGEDY', 26);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Busher, The', 374, 48, 16569, 'Visionary', 'FANTASY', 430);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Company, The', 283, 74, 9655, 'Organic', 'WESTERN', 9);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Return of the Living Dead, The', 295, 60, 34963, 'Cross-group', 'DRAMA', 201);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Kevin Smith: Too Fat For 40', 298, 63, 31635, 'emulation', 'THRILLER', 406);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Conan O''Brien Can''t Stop', 30, 13, 23325, '5th generation', 'THRILLER', 471);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Momo', 293, 51, 30567, 'Triple-buffered', 'FANTASY', 452);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Collision Course', 424, 79, 15070, 'extranet', 'DRAMA', 482);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Home', 201, 28, 7183, 'Visionary', 'WESTERN', 110);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Cursed', 394, 28, 6751, 'Object-based', 'FANTASY', 179);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('49th Parallel', 45, 100, 23709, 'cohesive', 'DRAMA', 236);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Shaggy Dog, The', 271, 16, 16096, 'Open-source', 'THRILLER', 59);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Reykjavik Whale Watching Massacre', 247, 36, 10717, 'Virtual', 'FANTASY', 336);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Come Blow Your Horn', 356, 3, 29600, 'adapter', 'TRAGEDY', 358);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Kisses for My President', 335, 47, 28245, 'Diverse', 'THRILLER', 412);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Ghost Story', 449, 51, 34507, 'Optimized', 'DRAMA', 365);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Bring It On: In It To Win It', 467, 2, 31792, 'Diverse', 'TRAGEDY', 179);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Hotel Terminus: The Life and Times of Klaus Barbie (Hôtel Terminus)', 484, 75, 3699, 'database', 'DRAMA', 405);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Sentinel, The', 260, 15, 33908, 'Focused', 'FANTASY', 73);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Last Unicorn, The', 127, 3, 20680, 'Team-oriented', 'DRAMA', 112);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Besotted', 276, 4, 10557, 'next generation', 'FANTASY', 272);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Level Five', 451, 72, 31495, 'logistical', 'WESTERN', 201);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('No Logo', 125, 83, 31812, 'Implemented', 'TRAGEDY', 203);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Ten Minutes Older: The Trumpet', 324, 53, 12014, 'adapter', 'TRAGEDY', 161);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Will Ferrell: You''re Welcome America - A Final Night with George W Bush', 234, 86, 498, 'flexibility', 'FANTASY', 482);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Agnosia', 184, 95, 4004, 'holistic', 'DRAMA', 359);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Victory (a.k.a. Escape to Victory)', 319, 33, 28929, 'user-facing', 'FANTASY', 131);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('You and Me (Ty i ya)', 268, 16, 4142, 'exuding', 'WESTERN', 170);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Animal Kingdom, The', 10, 94, 27315, 'productivity', 'THRILLER', 477);
insert into movie (name, coordinates_id, oscars_count, usa_box_office, tagline, genre, person_id) values ('Exists', 338, 53, 13851, 'asynchronous', 'TRAGEDY', 163);
